{
 "title": "iLO",
 "tags": [ "version 1.4" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(hpProductName,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cache battery status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpqDaAccelBattery{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server info",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "hpiLOsystemName{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hpProductName{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hpiLOFirmwareVersion{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cpqHeResMem2ModuleSize{instance=\"$server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hpiLOPowerMgmtStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"$server\",job=\"server_iLO_ping\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$server\"} /100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write cache status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpqDaAccelStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Physical Drive",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cpqDaPhyDrvStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqDaPhyDrvSize{instance=\"$server\"} * 1024*1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqDaPhyDrvRefHours{instance=\"$server\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqDaPhyDrvMediaType{instance=\"$server\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logical Drive",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "cpqDaLogDrvStatus{instance=\"$server\"}",
     "legendFormat": "drv {{logicaldrv}}"
    },
    {
     "expr": "cpqDaLogDrvCondition{instance=\"$server\"}",
     "legendFormat": "drv {{logicaldrv}}"
    },
    {
     "expr": "cpqDaLogDrvFaultTol{instance=\"$server\"}",
     "legendFormat": "drv {{logicaldrv}}"
    },
    {
     "expr": "cpqDaLogDrvSize{instance=\"$server\"}",
     "legendFormat": "drv {{logicaldrv}}"
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Power Module",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "cpqHeFltTolPowerSupplyCapacityMaximum{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyCapacityUsed{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyMainVoltage{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyCondition{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyErrorCondition{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyPresent{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolPowerSupplyStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "cpqHeFltTolFanCondition{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeFltTolFanPresent{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 19, "w": 7, "x": 9, "y": 21 },
   "targets": [
    {
     "expr": "cpqHeResMem2ModuleStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeResMem2ModuleCondition{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeResMem2ModuleSize{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "description": "degraded: The temperature sensor is outside of normal operating range\n\nfailed: The temperature sensor detects a condition that could permanently damage the system",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "cpqHeTemperatureThreshold{instance=\"$server\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeTemperatureCelsius{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpqHeTemperatureCondition{instance=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NIC",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "cpqNicIfPhysAdapterStatus{instance=\"$server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(cpqNicIfPhysAdapterStatus{instance=\"$server\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ambient temperature ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "cpqHeTemperatureCelsius{instance=\"$server\", locale=\"11\"}",
     "legendFormat": "{{sensorID}}"
    }
   ]
  }
 ]
}